### ISSUE TITLE
libbpf vendoring

### ISSUE THREAD

**Issue by danobi** [alexforster/libbpf-sys#10]
So libbpf source is currently vendored. And at libbpf-sys build time, cargo builds libbpf, builds shim for the inline functions, builds libbpf-sys rust bits, then links it all together.

I'm wondering why/if libbpf needs to be vendored. IIUC some *-sys libraries link against the system installed library (eg ncurses https://github.com/jeaye/ncurses-rs/blob/master/build.rs#L11).

The reason I bring this up is b/c I noticed that building CO-RE bpf programs requires libbpf headers so you'll need to install libbpf-devel anyways. And then you get some skew between libbpf-devel and libbpf-sys-built libbpf.

**Comment by alexforster** [comment]
We do dynamically link with libelf and libz, but I chose to vendor libbpf for a few reasons:

 * there aren't libbpf packages in many mainstream distros yet, and the few that do have them are either unstable or from very old kernels (I think – has this changed?)
 * it's a new and fast-moving codebase with major bugfixes and useful features being added frequently, so I think most users will want the lastest version
 * we'd still have to compile those xsk_ring shim functions, and they would require users to install `libbpf-dev[el]` (and a whole build toolchain along with it) so you lose all the advantages of dynamically linking

This will definitely be the right thing to do in the future, once libbpf has settled down and packages have made it into stable distros. At that point maybe we can rewrite the xsk_ring shims in Rust.

**Comment by alexforster** [comment]
> And then you get some skew between libbpf-devel and libbpf-sys-built libbpf.

The libbpf build process should be totally self-contained. The version of libbpf that it builds is statically linked in, and the C headers are never installed, so I thiiiink there should be no conflicts. Are you seeing any kind of breakage?

**Comment by danobi** [comment]
> We do dynamically link with libelf and libz, but I chose to vendor libbpf for a few reasons:

I see, that makes a lot of sense.

>  The version of libbpf that it builds is statically linked in, and the C headers are never installed, so I thiiiink there should be no conflicts. Are you seeing any kind of breakage?

No issues yet, but there's one thing I think could happen: the user installs a newer version of libbpf on their system and libbpf-sys is pegged to an older version. Then the user uses a bpf feature in their bpf prog that libbpf-sys doesn't yet know how to load. That could lead some confusing issues to debug.

One way to fix that could be a cargo feature flag to have libbpf-sys use the system installed libbpf. You could have the default behavior be the same as it is now. Would you take a PR for that?

**Comment by danobi** [comment]
> we'd still have to compile those xsk_ring shim functions, and they would require users to install libbpf-dev[el]

Hmm can't you have your own function decls for the APIs that are shimmed? The shims can dynamically link against system libbpf still, right?

**Comment by alexforster** [comment]
> Would you take a PR for that?

Absolutely.

> The shims can dynamically link against system libbpf still, right?

The reason they need to be shimmed is because in libbpf they're static inline, so they don't actually exist in libbpf.a/libbpf.so: https://gist.github.com/alexforster/2a37160d2f8b5d0cdf149abb4f1e0484

In order to compile them in to libbpf-sys, you have to use them inside of non-static/inline functions and then link to _those_ instead.

**Comment by danobi** [comment]
Ah I see now, didn't realize they were implemented in header. Not a very FFI-friendly decision.
