### ISSUE TITLE
bpf_tc_opts should use the MaybeUninit method of creating a default

### ISSUE THREAD

**Issue by mimullin-bbry** [alexforster/libbpf-sys#25]
Similar to bpf_tc_hook, struct bpf_tc_opts needs to be fully zeroed or the BPF verifier will complain "libbpf: bpf_tc_opts has non-zero extra bytes"

client code can do this work, but it would be nice if the libbpf-sys library did it for the clients

Question: How does rust-bindgen determine that bpf_tc_hooks needs a MaybeUninit zero method, while bpf_tc_opts does not?

**Comment by alexforster** [comment]
`bpf_tc_hook` implements `Default` manually...

```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bpf_tc_hook {
    pub sz: size_t,
    pub ifindex: ::std::os::raw::c_int,
    pub attach_point: bpf_tc_attach_point,
    pub parent: __u32,
}
impl Default for bpf_tc_hook {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
```

...but `bpf_tc_opts` also implements `Default`, except it does so by deriving...

```rust
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct bpf_tc_opts {
    pub sz: size_t,
    pub prog_fd: ::std::os::raw::c_int,
    pub flags: __u32,
    pub prog_id: __u32,
    pub handle: __u32,
    pub priority: __u32,
}
```

So constructing the default value of either of these should produce a struct with all members set to zero. Is the problem that there is non-zero data in the padding?

**Comment by alexforster** [comment]
This looks like a potential solution: rust-lang/rust-bindgen#2060
